# Project: Project1
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912" "-s" "-static"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-O3" "-pipe"
CFLAGS   = $(INCS) "-O3" "-pipe"
WINDRESFLAGS = 
RES      = Project1_private.res
OBJ      = ../music.o $(RES)
BIN      = Project1.exe
LINKOBJ  = "../music.o" "Project1_private.res"
CLEANOBJ = "..\music.o" "Project1_private.res" "Project1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Project1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Project1.exe" $(LIBS)

../music.o: ../music.cpp
	$(CXX) -c "../music.cpp" -o "../music.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gb18030

Project1_private.res: Project1_private.rc ../resource.rc 
	$(WINDRES) -i "Project1_private.rc" --input-format=rc -o "Project1_private.res" -O coff $(WINDRESFLAGS) 

